---
title: MarketplacePower
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sales@marketplacepower.agency
tagline: Amazon Marketplace management and expertise
keywords: Amazon management, Marketplace management, Amazon marketplace Agency, Amazon
  Consultants, Amazon Experts, Consultancy, Amazon Advertising, Amazon Expansion,
  Amazon Growth, Amazon Stores
address: MarketplacePower Ltd, Kemp House, 152 - 160 City Road, London, EC1V 2NX
description: MarketplacePower is a global amazon and ecommerce agency that focuses
  on helping retail brands grow on Amazon, their own e-commerce channels and other
  marketplaces.
baseurl: 
url: http://marketplacepower.agency
twitter_username: 
github_username: marketplacepower
excerpt_separator: "<!--more-->"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
future: true
paginate: 5
paginate_path: "/news/page:num"
permalink: "/news/:year/:title/"
