---
title: Marketplace Power
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tag:
    title: Tag
    output: true
  uploads:
    title: Uploads
    output: true
email: sales@marketplacepower.agency
tagline: Amazon Marketplace management and expertise
keywords: Amazon management, Marketplace management, Amazon marketplace Agency
address: MarketplacePower Ltd, Kemp House, 152 - 160 City Road, London, EC1V 2NX
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: http://marketplacepower.agency
twitter_username: 
github_username: 
excerpt_separator: "<!--more-->"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
future: true
paginate: 5
paginate_path: "/news/page:num"
permalink: "/news/:year/:title/"
