---
title: Marketplace Power
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sales@marketplacepower.agency
tagline: Amazon Marketplace management and expertise
keywords: Amazon management, Marketplace management, Amazon marketplace Agency, Amazon
  Consultants, Amazon Experts, Consultancy, Amazon Advertising, Amazon Expansion,
  Amazon Growth, Amazon Stores
address: MarketplacePower Ltd, Kemp House, 152 - 160 City Road, London, EC1V 2NX
description: MarketplacePower shares insight from vast  experience within Amazon to
  optimise all aspects of your Amazon business. For brands and retailers alike, we
  can advise or fully manage your amazon business.
baseurl: 
url: http://marketplacepower.agency
twitter_username: 
github_username: marketplacepower
excerpt_separator: "<!--more-->"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
future: true
paginate: 5
paginate_path: "/news/page:num"
permalink: "/news/:year/:title/"
